<?php
// generated by Poedit from order-daemon.en_US.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en_US','pot-creation-date'=>'2025-11-05 05:09+0200','po-revision-date'=>'2025-11-05 05:09+0200','translation-revision-date'=>'2025-11-05 05:09+0200','project-id-version'=>'Order Daemon for WooCommerce','x-generator'=>'Poedit 3.8','messages'=>[]];
