<?php
declare(strict_types=1);

namespace OrderDaemon\CompletionManager\Core;

/**
 * Log System Registries - Central Hub for Event Types and Status Definitions
 *
 * This file contains the registry functions that serve as the single source of truth
 * for all known log event types and their display statuses in the Order Daemon
 * For Woocommerce plugin. It implements the Registry Pattern to provide structured,
 * extensible, and maintainable logging architecture.
 *
 * REGISTRY PATTERN OVERVIEW:
 * =========================
 * 
 * The registry pattern centralizes the definition of all log events and statuses,
 * providing a structured approach to logging that enables:
 * - Consistent event categorization (core, debug, premium, custom)
 * - Dynamic summary generation using sprintf templates
 * - Standardized status handling with UI styling
 * - Easy extension for new event types
 * - Clear separation between internal and external logging
 * 
 * LOG CATEGORIES:
 * ==============
 * 
 * - 'core': Standard, essential events generated by the plugin
 * - 'debug': Verbose, developer-focused events (only logged when ODCM_DEBUG is active)
 * - 'premium': Events triggered by premium features (always saved, marked for UI)
 * - 'custom': Default category for external/third-party events
 * 
 * INTEGRATION WITH EXISTING ARCHITECTURE:
 * ======================================
 * 
 * This registry follows the established patterns in the plugin:
 * - Similar structure to OptionRegistry for consistency
 * - Integration with existing entitlement system
 * - Compatibility with current asynchronous logging via Action Scheduler
 *
 * @package OrderDaemon\CompletionManager\Core
 * @since   1.0.0
 * @author  OrderDaemon Development Team
 * @link    https://docs.OrderDaemon.com/completion-manager/audit-log-system
 */

// Prevent direct access to this file
if (!defined('WPINC')) {
    die;
}

/**
 * Get Log Event Types Registry - Single Source of Truth for Known Events
 *
 * This function returns a comprehensive registry of all known log event types
 * that can be generated by the Order Daemon plugin. Each event type includes
 * metadata for consistent logging, dynamic summary generation, and proper
 * categorization within the new audit log architecture.
 *
 * REGISTRY STRUCTURE:
 * ==================
 * 
 * Each event type is defined with the following properties:
 * - id: Unique event slug used for registry lookup
 * - label: Human-readable title for admin interfaces
 * - summary_template: sprintf template for dynamic summary generation
 * - default_status: Default status slug for this event type
 * - category: Log category (core, debug, premium, custom)
 * 
 * SUMMARY TEMPLATES:
 * =================
 * 
 * Templates use sprintf placeholders that are populated from context data:
 * - %d: Integer values (order IDs, counts, etc.)
 * - %s: String values (names, messages, etc.)
 * - %f: Float values (amounts, percentages, etc.)
 * 
 * Example: "Order #%d completed successfully" + ['order_id' => 123]
 * Result: "Order #123 completed successfully"
 * 
 * CATEGORIZATION SYSTEM:
 * =====================
 * 
 * Events are categorized to enable proper filtering and UI treatment:
 * 
 * CORE EVENTS: Essential plugin functionality
 * - Always logged regardless of debug mode
 * - Visible to all users in audit trail
 * - Critical for troubleshooting and monitoring
 * 
 * DEBUG EVENTS: Developer-focused verbose logging
 * - Only logged when ODCM_DEBUG constant is true
 * - Detailed execution flow and state information
 * - Hidden from production audit trails
 * 
 * PREMIUM EVENTS: Advanced feature logging
 * - Always saved to database regardless of license
 * - Marked for special UI treatment (premium badges)
 * - Used for upgrade prompts and feature discovery
 * 
 * EXTENSIBILITY:
 * =============
 * 
 * New event types can be added by:
 * 1. Adding entry to this registry function
 * 2. Using odcm_log_event() with the new event slug
 * 3. Providing appropriate context data for summary template
 * 
 * The registry is designed to be easily extended without breaking
 * existing functionality or requiring database changes.
 *
 * @since 1.0.0
 *
 * @return array<string, array<string, mixed>> {
 *     Associative array of event types keyed by event slug.
 *     
 *     @type array $event_slug {
 *         Individual event type definition.
 *         
 *         @type string $id               Unique event identifier (matches array key).
 *         @type string $label            Human-readable event name for admin UI.
 *         @type string $summary_template sprintf template for dynamic summary generation.
 *         @type string $default_status   Default status slug for this event type.
 *         @type string $category         Log category: 'core', 'debug', 'premium', or 'custom'.
 *     }
 * }
 *
 * @example
 * ```php
 * // Get all event types
 * $events = odcm_get_log_event_types();
 * 
 * // Look up specific event
 * $order_completed = $events['order_completed'];
 * echo $order_completed['label']; // "Order Completed"
 * 
 * // Generate dynamic summary
 * $summary = sprintf(
 *     $order_completed['summary_template'],
 *     123 // order_id from context
 * );
 * echo $summary; // "Order #123 completed successfully"
 * 
 * // Check event category
 * if ($order_completed['category'] === 'core') {
 *     // This is a core event - always log
 * }
 * ```
 */
function odcm_get_log_event_types(): array
{
    return [
        // === CORE EVENTS: Essential plugin functionality ===
        
        'order_completed' => [
            'id'               => 'order_completed',
            'label'            => __('Order Completed', 'order-daemon'),
            'summary_template' => __('Order #%d completed successfully', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        'order_processing_started' => [
            'id'               => 'order_processing_started',
            'label'            => __('Order Processing Started', 'order-daemon'),
            'summary_template' => __('Started processing order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'rule_matched' => [
            'id'               => 'rule_matched',
            'label'            => __('Rule Matched', 'order-daemon'),
            'summary_template' => __('Order #%d matched completion rule: %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'rule_skipped' => [
            'id'               => 'rule_skipped',
            'label'            => __('Rule Skipped', 'order-daemon'),
            'summary_template' => __('Order #%d skipped rule "%s": %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'invalid_order' => [
            'id'               => 'invalid_order',
            'label'            => __('Invalid Order Object', 'order-daemon'),
            'summary_template' => __('Order #%d could not be loaded or is invalid', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        
        'no_rules_found' => [
            'id'               => 'no_rules_found',
            'label'            => __('No Rules Found', 'order-daemon'),
            'summary_template' => __('No completion rules found for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'action_execution_failed' => [
            'id'               => 'action_execution_failed',
            'label'            => __('Action Execution Failed', 'order-daemon'),
            'summary_template' => __('Failed to execute action "%s" for order #%d: %s', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        
        'condition_check_failed' => [
            'id'               => 'condition_check_failed',
            'label'            => __('Condition Check Failed', 'order-daemon'),
            'summary_template' => __('Condition "%s" check failed for order #%d: %s', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        
        // === DEBUG EVENTS: Verbose developer logging ===
        
        'process_order_check_start' => [
            'id'               => 'process_order_check_start',
            'label'            => __('Process Order Check Started', 'order-daemon'),
            'summary_template' => __('Starting order check process for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        // === PHASE 1 NEW EVENTS: Deep condition and process tracking ===
        
        'condition_passed' => [
            'id'               => 'condition_passed',
            'label'            => __('Condition Passed', 'order-daemon'),
            'summary_template' => __('Condition "%s" passed for order #%d with value "%s"', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'condition_failed' => [
            'id'               => 'condition_failed',
            'label'            => __('Condition Failed', 'order-daemon'),
            'summary_template' => __('Condition "%s" failed for order #%d. Expected: "%s", Actual: "%s"', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'process_started' => [
            'id'               => 'process_started',
            'label'            => __('Process Started', 'order-daemon'),
            'summary_template' => __('Started processing workflow for order #%d', 'order-daemon'),
            'default_status'   => 'debug',
            'category'         => 'debug',
        ],
        
        'slow_execution' => [
            'id'               => 'slow_execution',
            'label'            => __('Slow Execution Warning', 'order-daemon'),
            'summary_template' => __('Order #%d processing took %dms, exceeding %dms threshold', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        
        'manual_status_change' => [
            'id'               => 'manual_status_change',
            'label'            => __('Manual Status Change', 'order-daemon'),
            'summary_template' => __('Order #%d status manually changed from "%s" to "%s" by user ID %d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            // Attribution-aware UI hints for renderers
            'attribution'      => [
                'show_source_plugin'    => true,
                'show_confidence_level' => true,
                'external_service_badges' => true,
            ],
        ],

        // === Attribution-Aware Events ===
        'webhook_status_change' => [
            'id'               => 'webhook_status_change',
            'label'            => __('Webhook Status Change', 'order-daemon'),
            'summary_template' => __('Order #%d status changed from "%s" to "%s" by %s webhook', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => false,
                'show_confidence_level' => true,
                'external_service_badges' => true,
            ],
        ],
        'plugin_automated_change' => [
            'id'               => 'plugin_automated_change',
            'label'            => __('Plugin Automated Change', 'order-daemon'),
            'summary_template' => __('Order #%d automatically updated by %s plugin via %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => true,
                'show_confidence_level' => true,
                'external_service_badges' => false,
            ],
        ],
        'api_status_change' => [
            'id'               => 'api_status_change',
            'label'            => __('API Status Change', 'order-daemon'),
            'summary_template' => __('Order #%d status changed from "%s" to "%s" via REST API', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => false,
                'show_confidence_level' => false,
                'external_service_badges' => false,
            ],
        ],
        'external_service_action' => [
            'id'               => 'external_service_action',
            'label'            => __('External Service Action', 'order-daemon'),
            'summary_template' => __('External service %s performed "%s" for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => false,
                'show_confidence_level' => true,
                'external_service_badges' => true,
            ],
        ],
        
        // === Refund & Deletion Events (Core) ===
        'order_partially_refunded' => [
            'id'               => 'order_partially_refunded',
            'label'            => __('Order Partially Refunded', 'order-daemon'),
            'summary_template' => __('Order #%d partially refunded: %s (%d%% of total)', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'order_fully_refunded' => [
            'id'               => 'order_fully_refunded',
            'label'            => __('Order Fully Refunded', 'order-daemon'),
            'summary_template' => __('Order #%d fully refunded: %s', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'refund_created' => [
            'id'               => 'refund_created',
            'label'            => __('Refund Created', 'order-daemon'),
            'summary_template' => __('Refund #%d created for order #%d: %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        'refund_deleted' => [
            'id'               => 'refund_deleted',
            'label'            => __('Refund Deleted', 'order-daemon'),
            'summary_template' => __('Refund #%d deleted for order #%d', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'order_deleted' => [
            'id'               => 'order_deleted',
            'label'            => __('Order Deleted', 'order-daemon'),
            'summary_template' => __('Order #%d deleted by %s', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        'order_trashed' => [
            'id'               => 'order_trashed',
            'label'            => __('Order Trashed', 'order-daemon'),
            'summary_template' => __('Order #%d moved to trash by %s', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'order_restored' => [
            'id'               => 'order_restored',
            'label'            => __('Order Restored', 'order-daemon'),
            'summary_template' => __('Order #%d restored from trash by %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'step_timing' => [
            'id'               => 'step_timing',
            'label'            => __('Step Timing', 'order-daemon'),
            'summary_template' => __('Step "%s" took %dms to execute', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'no_match_found' => [
            'id'               => 'no_match_found',
            'label'            => __('No Rules Matched', 'order-daemon'),
            'summary_template' => __('No completion rules matched for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'rule_evaluation_start' => [
            'id'               => 'rule_evaluation_start',
            'label'            => __('Rule Evaluation Started', 'order-daemon'),
            'summary_template' => __('Evaluating rule "%s" for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'condition_evaluation' => [
            'id'               => 'condition_evaluation',
            'label'            => __('Condition Evaluation', 'order-daemon'),
            'summary_template' => __('Condition "%s" for order #%d: %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'action_execution_start' => [
            'id'               => 'action_execution_start',
            'label'            => __('Action Execution Started', 'order-daemon'),
            'summary_template' => __('Executing action "%s" for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'database_query_executed' => [
            'id'               => 'database_query_executed',
            'label'            => __('Database Query Executed', 'order-daemon'),
            'summary_template' => __('Executed database query: %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        // === PREMIUM EVENTS: Advanced feature logging ===
        
        'advanced_condition_matched' => [
            'id'               => 'advanced_condition_matched',
            'label'            => __('Advanced Condition Matched', 'order-daemon'),
            'summary_template' => __('Order #%d matched premium condition: %s', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        'custom_email_sent' => [
            'id'               => 'custom_email_sent',
            'label'            => __('Custom Email Sent', 'order-daemon'),
            'summary_template' => __('Custom email sent for order #%d to %s', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        'advanced_action_executed' => [
            'id'               => 'advanced_action_executed',
            'label'            => __('Advanced Action Executed', 'order-daemon'),
            'summary_template' => __('Premium action "%s" executed for order #%d', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        'bulk_operation_completed' => [
            'id'               => 'bulk_operation_completed',
            'label'            => __('Bulk Operation Completed', 'order-daemon'),
            'summary_template' => __('Bulk operation completed: %d orders processed', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        // === SYSTEM EVENTS: Internal plugin operations ===
        
        'plugin_activated' => [
            'id'               => 'plugin_activated',
            'label'            => __('Plugin Activated', 'order-daemon'),
            'summary_template' => __('Order Daemon plugin activated (version %s)', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        'database_upgraded' => [
            'id'               => 'database_upgraded',
            'label'            => __('Database Upgraded', 'order-daemon'),
            'summary_template' => __('Database schema upgraded from version %s to %s', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        'settings_updated' => [
            'id'               => 'settings_updated',
            'label'            => __('Settings Updated', 'order-daemon'),
            'summary_template' => __('Plugin settings updated by user %s', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'cleanup_task' => [
            'id'               => 'cleanup_task',
            'label'            => __('Log Cleanup Task', 'order-daemon'),
            'summary_template' => __('Log cleanup completed: %d entries removed (retention: %d days)', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'admin_reprocess_orders' => [
            'id'               => 'admin_reprocess_orders',
            'label'            => __('Admin Reprocess Orders', 'order-daemon'),
            'summary_template' => __('Admin user "%s" initiated reprocessing of %d pending orders', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        // === TESTING EVENTS: Comprehensive status and component validation ===
        
        // SUCCESS STATUS EVENTS
        'api_call_report' => [
            'id'               => 'api_call_report',
            'label'            => __('Test: API Call Success', 'order-daemon'),
            'summary_template' => __('Successful API integration for order #%d', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        'rule_eval_matched' => [
            'id'               => 'rule_eval_matched',
            'label'            => __('Test: Rule Match Success', 'order-daemon'),
            'summary_template' => __('Rule evaluation successful for order #%d', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        'db_query_success' => [
            'id'               => 'db_query_success',
            'label'            => __('Test: Database Success', 'order-daemon'),
            'summary_template' => __('Database operation completed successfully', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        // ERROR STATUS EVENTS
        'error_report_stack_trace' => [
            'id'               => 'error_report_stack_trace',
            'label'            => __('Test: Critical Error', 'order-daemon'),
            'summary_template' => __('Critical system error with stack trace for order #%d', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'debug',
        ],
        
        'db_query_failed' => [
            'id'               => 'db_query_failed',
            'label'            => __('Test: Database Error', 'order-daemon'),
            'summary_template' => __('Database operation failed with error', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'debug',
        ],
        
        // WARNING STATUS EVENTS
        'error_report_simple_string' => [
            'id'               => 'error_report_simple_string',
            'label'            => __('Test: Warning Message', 'order-daemon'),
            'summary_template' => __('Warning condition detected for order #%d', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        'db_query_slow' => [
            'id'               => 'db_query_slow',
            'label'            => __('Test: Performance Warning', 'order-daemon'),
            'summary_template' => __('Slow database query detected (performance warning)', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        // INFO STATUS EVENTS
        'performance_report' => [
            'id'               => 'performance_report',
            'label'            => __('Test: Performance Info', 'order-daemon'),
            'summary_template' => __('Performance monitoring report for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        'woocommerce_report' => [
            'id'               => 'woocommerce_report',
            'label'            => __('Test: WooCommerce Info', 'order-daemon'),
            'summary_template' => __('WooCommerce integration data for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // NOTICE STATUS EVENTS
        'system_info_report' => [
            'id'               => 'system_info_report',
            'label'            => __('Test: System Notice', 'order-daemon'),
            'summary_template' => __('System information notice and monitoring data', 'order-daemon'),
            'default_status'   => 'notice',
            'category'         => 'test',
        ],
        
        'rule_eval_no_match' => [
            'id'               => 'rule_eval_no_match',
            'label'            => __('Test: Rule No Match', 'order-daemon'),
            'summary_template' => __('Rule evaluation notice: no match for order #%d', 'order-daemon'),
            'default_status'   => 'notice',
            'category'         => 'test',
        ],
        
        // CRITICAL STATUS EVENTS
        'error_report_wp_error' => [
            'id'               => 'error_report_wp_error',
            'label'            => __('Test: Critical WP Error', 'order-daemon'),
            'summary_template' => __('Critical WordPress error requiring immediate attention', 'order-daemon'),
            'default_status'   => 'critical',
            'category'         => 'debug',
        ],
        
        // COMPLETED STATUS EVENTS
        'fallback_data' => [
            'id'               => 'fallback_data',
            'label'            => __('Test: Operation Completed', 'order-daemon'),
            'summary_template' => __('Fallback operation completed for order #%d', 'order-daemon'),
            'default_status'   => 'completed',
            'category'         => 'test',
        ],
        
        // DEBUG STATUS EVENTS
        'debug_trace_report' => [
            'id'               => 'debug_trace_report',
            'label'            => __('Test: Debug Trace', 'order-daemon'),
            'summary_template' => __('Debug trace information for development', 'order-daemon'),
            'default_status'   => 'debug',
            'category'         => 'test',
        ],
        
        // PENDING STATUS EVENTS
        'async_operation_pending' => [
            'id'               => 'async_operation_pending',
            'label'            => __('Test: Pending Operation', 'order-daemon'),
            'summary_template' => __('Asynchronous operation pending for order #%d', 'order-daemon'),
            'default_status'   => 'pending',
            'category'         => 'test',
        ],
        
        // SKIPPED STATUS EVENTS
        'operation_skipped' => [
            'id'               => 'operation_skipped',
            'label'            => __('Test: Operation Skipped', 'order-daemon'),
            'summary_template' => __('Operation skipped due to conditions for order #%d', 'order-daemon'),
            'default_status'   => 'skipped',
            'category'         => 'test',
        ],
               
        // Pure API Events - Only API detection keys
        'pure_api_event' => [
            'id'               => 'pure_api_event',
            'label'            => __('Test: Pure API Event', 'order-daemon'),
            'summary_template' => __('Pure API operation for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Pure Database Events - Only database detection keys
        'pure_database_event' => [
            'id'               => 'pure_database_event',
            'label'            => __('Test: Pure Database Event', 'order-daemon'),
            'summary_template' => __('Pure database operation for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Complex Multi-API Events - Multiple API calls in single payload
        'complex_multi_api_event' => [
            'id'               => 'complex_multi_api_event',
            'label'            => __('Test: Complex Multi-API Event', 'order-daemon'),
            'summary_template' => __('Complex multi-API operation for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Webhook Processing Events - API + WooCommerce + Performance
        'webhook_processing_event' => [
            'id'               => 'webhook_processing_event',
            'label'            => __('Test: Webhook Processing Event', 'order-daemon'),
            'summary_template' => __('Webhook processing for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Background Task Events - System + Performance + Database
        'background_task_event' => [
            'id'               => 'background_task_event',
            'label'            => __('Test: Background Task Event', 'order-daemon'),
            'summary_template' => __('Background task processing for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Integration Events - Third-party plugin interactions
        'integration_event' => [
            'id'               => 'integration_event',
            'label'            => __('Test: Integration Event', 'order-daemon'),
            'summary_template' => __('Third-party integration for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Import/Export Events - Database + Performance + System + API
        'import_export_event' => [
            'id'               => 'import_export_event',
            'label'            => __('Test: Import/Export Event', 'order-daemon'),
            'summary_template' => __('Import/export operation for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // === STRESS TEST EVENTS ===
        
        // Large Payload Tests - Very large JSON objects (>100KB)
        'large_payload_stress_test' => [
            'id'               => 'large_payload_stress_test',
            'label'            => __('Test: Large Payload Stress', 'order-daemon'),
            'summary_template' => __('Large payload stress test for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Deep Nesting Tests - Deeply nested data structures (10+ levels)
        'deep_nesting_stress_test' => [
            'id'               => 'deep_nesting_stress_test',
            'label'            => __('Test: Deep Nesting Stress', 'order-daemon'),
            'summary_template' => __('Deep nesting stress test for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Long Text Tests - Very long error messages, stack traces (>10,000 chars)
        'long_text_stress_test' => [
            'id'               => 'long_text_stress_test',
            'label'            => __('Test: Long Text Stress', 'order-daemon'),
            'summary_template' => __('Long text stress test for order #%d', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'test',
        ],
        
        // Unicode Tests - Special characters, emojis, international text
        'unicode_stress_test' => [
            'id'               => 'unicode_stress_test',
            'label'            => __('Test: Unicode Stress', 'order-daemon'),
            'summary_template' => __('Unicode stress test for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Special Character Tests - HTML entities, SQL injection attempts, XSS
        'special_char_stress_test' => [
            'id'               => 'special_char_stress_test',
            'label'            => __('Test: Special Character Stress', 'order-daemon'),
            'summary_template' => __('Special character stress test for order #%d', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        // Memory Stress Tests - Large arrays, binary data representations
        'memory_stress_test' => [
            'id'               => 'memory_stress_test',
            'label'            => __('Test: Memory Stress', 'order-daemon'),
            'summary_template' => __('Memory stress test for order #%d', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        // Performance Edge Cases - Very slow queries (>10s), memory exhaustion
        'performance_edge_stress_test' => [
            'id'               => 'performance_edge_stress_test',
            'label'            => __('Test: Performance Edge Stress', 'order-daemon'),
            'summary_template' => __('Performance edge case stress test for order #%d', 'order-daemon'),
            'default_status'   => 'critical',
            'category'         => 'test',
        ],
        
        // === INTEGRATION SCENARIO EVENTS ===
        
        // Multi-Component Events - Single events triggering 4+ renderers
        'multi_component_integration' => [
            'id'               => 'multi_component_integration',
            'label'            => __('Test: Multi-Component Integration', 'order-daemon'),
            'summary_template' => __('Multi-component integration test for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Workflow Progression - Related events showing order processing flow
        'workflow_progression_start' => [
            'id'               => 'workflow_progression_start',
            'label'            => __('Test: Workflow Start', 'order-daemon'),
            'summary_template' => __('Workflow progression started for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        'workflow_progression_middle' => [
            'id'               => 'workflow_progression_middle',
            'label'            => __('Test: Workflow Progress', 'order-daemon'),
            'summary_template' => __('Workflow progression continuing for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        'workflow_progression_end' => [
            'id'               => 'workflow_progression_end',
            'label'            => __('Test: Workflow Complete', 'order-daemon'),
            'summary_template' => __('Workflow progression completed for order #%d', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        // Cross-Reference Samples - Events referencing other log entries
        'cross_reference_event' => [
            'id'               => 'cross_reference_event',
            'label'            => __('Test: Cross-Reference Event', 'order-daemon'),
            'summary_template' => __('Cross-reference event for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Time-Series Samples - Events showing progression over time
        'time_series_event' => [
            'id'               => 'time_series_event',
            'label'            => __('Test: Time-Series Event', 'order-daemon'),
            'summary_template' => __('Time-series progression for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Error Recovery Samples - Error → Retry → Success sequences
        'error_recovery_failure' => [
            'id'               => 'error_recovery_failure',
            'label'            => __('Test: Recovery Failure', 'order-daemon'),
            'summary_template' => __('Error recovery failure for order #%d', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'test',
        ],
        
        'error_recovery_retry' => [
            'id'               => 'error_recovery_retry',
            'label'            => __('Test: Recovery Retry', 'order-daemon'),
            'summary_template' => __('Error recovery retry for order #%d', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        'error_recovery_success' => [
            'id'               => 'error_recovery_success',
            'label'            => __('Test: Recovery Success', 'order-daemon'),
            'summary_template' => __('Error recovery success for order #%d', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        // Real-World Scenarios - Complete order processing workflows
        'real_world_order_workflow' => [
            'id'               => 'real_world_order_workflow',
            'label'            => __('Test: Real-World Order Workflow', 'order-daemon'),
            'summary_template' => __('Real-world order workflow for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Plugin Interaction Samples - Events from multiple plugins
        'plugin_interaction_event' => [
            'id'               => 'plugin_interaction_event',
            'label'            => __('Test: Plugin Interaction', 'order-daemon'),
            'summary_template' => __('Plugin interaction event for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],

        // === REFUND & DELETION TRACKING EVENTS ===
        'order_partially_refunded' => [
            'id'               => 'order_partially_refunded',
            'label'            => __('Order Partially Refunded', 'order-daemon'),
            'summary_template' => __('Order #%d partially refunded', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],

        'order_fully_refunded' => [
            'id'               => 'order_fully_refunded',
            'label'            => __('Order Fully Refunded', 'order-daemon'),
            'summary_template' => __('Order #%d fully refunded', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],

        'refund_created' => [
            'id'               => 'refund_created',
            'label'            => __('Refund Created', 'order-daemon'),
            'summary_template' => __('Refund created for order #%d', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],

        'refund_deleted' => [
            'id'               => 'refund_deleted',
            'label'            => __('Refund Deleted', 'order-daemon'),
            'summary_template' => __('Refund deleted for order #%d', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],

        'order_deleted' => [
            'id'               => 'order_deleted',
            'label'            => __('Order Deleted', 'order-daemon'),
            'summary_template' => __('Order #%d deleted', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],

        'order_trashed' => [
            'id'               => 'order_trashed',
            'label'            => __('Order Trashed', 'order-daemon'),
            'summary_template' => __('Order #%d moved to trash', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],

        'order_restored' => [
            'id'               => 'order_restored',
            'label'            => __('Order Restored', 'order-daemon'),
            'summary_template' => __('Order #%d restored from trash', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
    ];
}

/**
 * Get Log Status Registry - Standardized Status Definitions with UI Styling
 *
 * This function returns a comprehensive registry of all available log statuses
 * that can be used throughout the audit log system. Each status includes
 * display properties for consistent UI rendering and user experience.
 *
 * STATUS SYSTEM OVERVIEW:
 * ======================
 * 
 * The status system provides standardized categorization of log events
 * based on their outcome or severity level. This enables:
 * - Consistent visual representation across the admin interface
 * - Effective filtering and searching capabilities
 * - Clear communication of event importance to users
 * - Standardized CSS styling for status indicators
 * 
 * UI INTEGRATION:
 * ==============
 * 
 * Each status includes a CSS class that corresponds to styling in the
 * plugin's admin.css file. The classes follow the pattern:
 * odcm-status-pill-{status}
 * 
 * This enables consistent "pill" style status indicators throughout
 * the audit trail interface with appropriate colors and styling.
 * 
 * EXTENSIBILITY:
 * =============
 * 
 * New statuses can be added by:
 * 1. Adding entry to this registry function
 * 2. Adding corresponding CSS styles to admin.css
 * 3. Using the new status in event logging calls
 * 
 * The system is designed to be easily extended without breaking
 * existing functionality or requiring code changes elsewhere.
 *
 * @since 1.0.0
 *
 * @return array<string, array<string, string>> {
 *     Associative array of status definitions keyed by status slug.
 *     
 *     @type array $status_slug {
 *         Individual status definition.
 *         
 *         @type string $label     Translatable display text for the status.
 *         @type string $css_class CSS class name for styling the status pill.
 *     }
 * }
 *
 * @example
 * ```php
 * // Get all available statuses
 * $statuses = odcm_get_log_statuses();
 * 
 * // Render status pill in UI
 * $status = 'success';
 * if (isset($statuses[$status])) {
 *     $status_data = $statuses[$status];
 *     echo '<span class="' . esc_attr($status_data['css_class']) . '">';
 *     echo esc_html($status_data['label']);
 *     echo '</span>';
 * }
 * 
 * // Validate status before logging
 * $requested_status = 'custom_status';
 * if (!array_key_exists($requested_status, $statuses)) {
 *     $requested_status = 'info'; // Default fallback
 * }
 * 
 * // Generate status dropdown for filtering
 * foreach ($statuses as $slug => $data) {
 *     echo '<option value="' . esc_attr($slug) . '">';
 *     echo esc_html($data['label']);
 *     echo '</option>';
 * }
 * ```
 */
function odcm_get_log_statuses(): array
{
    return [
        'success' => [
            'label'     => __('Success', 'order-daemon'),
            'css_class' => 'odcm-status-pill--success',
            'code'      => 1,
        ],
        
        'error' => [
            'label'     => __('Error', 'order-daemon'),
            'css_class' => 'odcm-status-pill--error',
            'code'      => 2,
        ],
        
        'warning' => [
            'label'     => __('Warning', 'order-daemon'),
            'css_class' => 'odcm-status-pill--warning',
            'code'      => 3,
        ],
        
        'info' => [
            'label'     => __('Info', 'order-daemon'),
            'css_class' => 'odcm-status-pill--info',
            'code'      => 4,
        ],
        
        'notice' => [
            'label'     => __('Notice', 'order-daemon'),
            'css_class' => 'odcm-status-pill--notice',
            'code'      => 5,
        ],
        
        'debug' => [
            'label'     => __('Debug', 'order-daemon'),
            'css_class' => 'odcm-status-pill--debug',
            'code'      => 6,
        ],
        
        'critical' => [
            'label'     => __('Critical', 'order-daemon'),
            'css_class' => 'odcm-status-pill--critical',
            'code'      => 7,
        ],
        
        'pending' => [
            'label'     => __('Pending', 'order-daemon'),
            'css_class' => 'odcm-status-pill--notice',
            'code'      => 8,
        ],
        
        'skipped' => [
            'label'     => __('Skipped', 'order-daemon'),
            'css_class' => 'odcm-status-pill--notice',
            'code'      => 9,
        ],
        
        'completed' => [
            'label'     => __('Completed', 'order-daemon'),
            'css_class' => 'odcm-status-pill--success',
            'code'      => 10,
        ],
    ];
}

/**
 * Get Log Sources Registry - Sources of audit log events with encoding
 *
 * @since 1.0.0
 * @return array<string, array<string, mixed>>
 */
function odcm_get_log_sources(): array
{
    return [
        'system' => [
            'label' => __('System', 'order-daemon'),
            'code'  => 1,
        ],
        'manual' => [
            'label' => __('Manual', 'order-daemon'), 
            'code'  => 2,
        ],
        'webhook' => [
            'label' => __('Webhook', 'order-daemon'),
            'code'  => 3,
        ],
        'api' => [
            'label' => __('API', 'order-daemon'),
            'code'  => 4,
        ],
        'scheduled' => [
            'label' => __('Scheduled', 'order-daemon'),
            'code'  => 5,
        ],
        'processor' => [
            'label' => __('Event Processor', 'order-daemon'),
            'code'  => 6,
        ],
        'logger' => [
            'label' => __('Logger', 'order-daemon'),
            'code'  => 7,
        ],
    ];
}

/**
 * Encode status string to integer code
 *
 * @param string $status Status string
 * @return int Status code
 */
function odcm_encode_status(string $status): int 
{
    $statuses = odcm_get_log_statuses();
    return $statuses[$status]['code'] ?? 4; // Default to 'info'
}

/**
 * Decode status code to string
 *
 * @param int $code Status code
 * @return string Status string
 */
function odcm_decode_status(int $code): string 
{
    static $reverse_map = null;
    if ($reverse_map === null) {
        $statuses = odcm_get_log_statuses();
        foreach ($statuses as $status => $data) {
            $reverse_map[$data['code']] = $status;
        }
    }
    return $reverse_map[$code] ?? 'info';
}

/**
 * Encode source string to integer code
 *
 * @param string $source Source string
 * @return int Source code
 */
function odcm_encode_source(string $source): int 
{
    $sources = odcm_get_log_sources();
    return $sources[$source]['code'] ?? 1; // Default to 'system'
}

/**
 * Decode source code to string
 *
 * @param int $code Source code
 * @return string Source string
 */
function odcm_decode_source(int $code): string 
{
    static $reverse_map = null;
    if ($reverse_map === null) {
        $sources = odcm_get_log_sources();
        foreach ($sources as $source => $data) {
            $reverse_map[$data['code']] = $source;
        }
    }
    $result = $reverse_map[$code] ?? 'system';
    return (string) $result; // Ensure we always return a string
}
