<?php
declare(strict_types=1);

namespace OrderDaemon\CompletionManager\Core;

/**
 * Log System Registries - Central Hub for Event Types and Status Definitions
 *
 * This file contains the registry functions that serve as the single source of truth
 * for all known log event types and their display statuses in the Order Daemon
 * For Woocommerce plugin. It implements the Registry Pattern to provide structured,
 * extensible, and maintainable logging architecture.
 *
 * REGISTRY PATTERN OVERVIEW:
 * =========================
 * 
 * The registry pattern centralizes the definition of all log events and statuses,
 * providing a structured approach to logging that enables:
 * - Consistent event categorization (core, debug, premium, custom)
 * - Dynamic summary generation using sprintf templates
 * - Standardized status handling with UI styling
 * - Easy extension for new event types
 * - Clear separation between internal and external logging
 * 
 * LOG CATEGORIES:
 * ==============
 * 
 * - 'core': Standard, essential events generated by the plugin
 * - 'debug': Verbose, developer-focused events (only logged when ODCM_DEBUG is active)
 * - 'premium': Events triggered by premium features (always saved, marked for UI)
 * - 'custom': Default category for external/third-party events
 * 
 * INTEGRATION WITH EXISTING ARCHITECTURE:
 * ======================================
 * 
 * This registry follows the established patterns in the plugin:
 * - Similar structure to OptionRegistry for consistency
 * - Integration with existing entitlement system
 * - Compatibility with current asynchronous logging via Action Scheduler
 *
 * @package OrderDaemon\CompletionManager\Core
 * @since   1.0.0
 * @author  OrderDaemon Development Team
 * @link    https://docs.OrderDaemon.com/completion-manager/audit-log-system
 */

// Prevent direct access to this file
if (!defined('WPINC')) {
    die;
}

/**
 * Get Log Event Types Registry - Single Source of Truth for Known Events
 *
 * This function returns a comprehensive registry of all known log event types
 * that can be generated by the Order Daemon plugin. Each event type includes
 * metadata for consistent logging, dynamic summary generation, and proper
 * categorization within the new audit log architecture.
 *
 * REGISTRY STRUCTURE:
 * ==================
 * 
 * Each event type is defined with the following properties:
 * - id: Unique event slug used for registry lookup
 * - label: Human-readable title for admin interfaces
 * - summary_template: sprintf template for dynamic summary generation
 * - default_status: Default status slug for this event type
 * - category: Log category (core, debug, premium, custom)
 * 
 * SUMMARY TEMPLATES:
 * =================
 * 
 * Templates use sprintf placeholders that are populated from context data:
 * - %d: Integer values (order IDs, counts, etc.)
 * - %s: String values (names, messages, etc.)
 * - %f: Float values (amounts, percentages, etc.)
 * 
 * Example: "Order #%d completed successfully" + ['order_id' => 123]
 * Result: "Order #123 completed successfully"
 * 
 * CATEGORIZATION SYSTEM:
 * =====================
 * 
 * Events are categorized to enable proper filtering and UI treatment:
 * 
 * CORE EVENTS: Essential plugin functionality
 * - Always logged regardless of debug mode
 * - Visible to all users in audit trail
 * - Critical for troubleshooting and monitoring
 * 
 * DEBUG EVENTS: Developer-focused verbose logging
 * - Only logged when ODCM_DEBUG constant is true
 * - Detailed execution flow and state information
 * - Hidden from production audit trails
 * 
 * PREMIUM EVENTS: Advanced feature logging
 * - Always saved to database regardless of license
 * - Marked for special UI treatment (premium badges)
 * - Used for upgrade prompts and feature discovery
 * 
 * EXTENSIBILITY:
 * =============
 * 
 * New event types can be added by:
 * 1. Adding entry to this registry function
 * 2. Using odcm_log_event() with the new event slug
 * 3. Providing appropriate context data for summary template
 * 
 * The registry is designed to be easily extended without breaking
 * existing functionality or requiring database changes.
 *
 * @since 1.0.0
 *
 * @return array<string, array<string, mixed>> {
 *     Associative array of event types keyed by event slug.
 *     
 *     @type array $event_slug {
 *         Individual event type definition.
 *         
 *         @type string $id               Unique event identifier (matches array key).
 *         @type string $label            Human-readable event name for admin UI.
 *         @type string $summary_template sprintf template for dynamic summary generation.
 *         @type string $default_status   Default status slug for this event type.
 *         @type string $category         Log category: 'core', 'debug', 'premium', or 'custom'.
 *     }
 * }
 *
 * @example
 * ```php
 * // Get all event types
 * $events = odcm_get_log_event_types();
 * 
 * // Look up specific event
 * $order_completed = $events['order_completed'];
 * echo $order_completed['label']; // "Order Completed"
 * 
 * // Generate dynamic summary
 * $summary = sprintf(
 *     $order_completed['summary_template'],
 *     123 // order_id from context
 * );
 * echo $summary; // "Order #123 completed successfully"
 * 
 * // Check event category
 * if ($order_completed['category'] === 'core') {
 *     // This is a core event - always log
 * }
 * ```
 */
function odcm_get_log_event_types(): array
{
    return [
        // === CORE EVENTS: Essential plugin functionality ===
        
        'order_completed' => [
            'id'               => 'order_completed',
            'label'            => __('core.log.event.order_completed', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.event.order_completed_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        'order_processing_started' => [
            'id'               => 'order_processing_started',
            'label'            => __('core.log.event.order_processing_started', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.event.order_processing_started_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'rule_matched' => [
            'id'               => 'rule_matched',
            'label'            => __('core.log.event.rule_matched', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Rule name */
            'summary_template' => __('core.log.event.rule_matched_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'rule_skipped' => [
            'id'               => 'rule_skipped',
            'label'            => __('core.log.event.rule_skipped', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Rule name, 3: Skip reason */
            'summary_template' => __('core.log.event.rule_skipped_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'invalid_order' => [
            'id'               => 'invalid_order',
            'label'            => __('core.log.event.invalid_order', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.event.invalid_order_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        
        'no_rules_found' => [
            'id'               => 'no_rules_found',
            'label'            => __('core.log.event.no_rules_found', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.event.no_rules_found_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'action_execution_failed' => [
            'id'               => 'action_execution_failed',
            'label'            => __('core.log.event.action_execution_failed', 'order-daemon'),
            /* translators: 1: Action name, 2: Order ID number, 3: Error message */
            'summary_template' => __('core.log.event.action_execution_failed_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        
        'condition_check_failed' => [
            'id'               => 'condition_check_failed',
            'label'            => __('core.log.event.condition_check_failed', 'order-daemon'),
            /* translators: 1: Condition name, 2: Order ID number, 3: Error message */
            'summary_template' => __('core.log.event.condition_check_failed_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        
        // === DEBUG EVENTS: Verbose developer logging ===
        
        'process_order_check_start' => [
            'id'               => 'process_order_check_start',
            'label'            => __('core.log.event.process_check_started', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.event.process_check_started_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        // === PHASE 1 NEW EVENTS: Deep condition and process tracking ===
        
        'condition_passed' => [
            'id'               => 'condition_passed',
            'label'            => __('core.log.event.condition_passed', 'order-daemon'),
            /* translators: 1: Condition name, 2: Order ID number, 3: Condition value */
            'summary_template' => __('core.log.event.condition_passed_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'condition_failed' => [
            'id'               => 'condition_failed',
            'label'            => __('core.log.event.condition_failed', 'order-daemon'),
            /* translators: 1: Condition name, 2: Order ID number, 3: Expected value, 4: Actual value */
            'summary_template' => __('core.log.event.condition_failed_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'process_started' => [
            'id'               => 'process_started',
            'label'            => __('core.log.event.process_started', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.event.process_started_message', 'order-daemon'),
            'default_status'   => 'debug',
            'category'         => 'debug',
        ],
        
        'slow_execution' => [
            'id'               => 'slow_execution',
            'label'            => __('core.log.event.slow_execution', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Execution time in milliseconds, 3: Threshold in milliseconds */
            'summary_template' => __('core.log.event.slow_execution_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        
        'manual_status_change' => [
            'id'               => 'manual_status_change',
            'label'            => __('core.log.event.manual_status_change', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Previous status, 3: New status, 4: User ID */
            'summary_template' => __('core.log.event.manual_status_change_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            // Attribution-aware UI hints for renderers
            'attribution'      => [
                'show_source_plugin'    => true,
                'show_confidence_level' => true,
                'external_service_badges' => true,
            ],
        ],

        // === Attribution-Aware Events ===
        'webhook_status_change' => [
            'id'               => 'webhook_status_change',
            'label'            => __('core.log.event.webhook_status_change', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Previous status, 3: New status, 4: Webhook service name */
            'summary_template' => __('core.log.event.webhook_status_change_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => false,
                'show_confidence_level' => true,
                'external_service_badges' => true,
            ],
        ],
        'plugin_automated_change' => [
            'id'               => 'plugin_automated_change',
            'label'            => __('core.log.event.plugin_automated_change', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Plugin name, 3: Method used */
            'summary_template' => __('core.log.event.plugin_automated_change_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => true,
                'show_confidence_level' => true,
                'external_service_badges' => false,
            ],
        ],
        'api_status_change' => [
            'id'               => 'api_status_change',
            'label'            => __('core.log.event.api_status_change', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Previous status, 3: New status */
            'summary_template' => __('core.log.event.api_status_change_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => false,
                'show_confidence_level' => false,
                'external_service_badges' => false,
            ],
        ],
        'external_service_action' => [
            'id'               => 'external_service_action',
            'label'            => __('core.log.event.external_service_action', 'order-daemon'),
            /* translators: 1: Service name, 2: Action performed, 3: Order ID number */
            'summary_template' => __('core.log.event.external_service_action_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
            'attribution'      => [
                'show_source_plugin'    => false,
                'show_confidence_level' => true,
                'external_service_badges' => true,
            ],
        ],
        
        // === Refund & Deletion Events (Core) ===
        'order_partially_refunded' => [
            'id'               => 'order_partially_refunded',
            'label'            => __('core.log.event.order_partially_refunded', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Refund amount, 3: Percentage of total */
            'summary_template' => __('core.log.event.order_partially_refunded_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'order_fully_refunded' => [
            'id'               => 'order_fully_refunded',
            'label'            => __('core.log.event.order_fully_refunded', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Refund amount */
            'summary_template' => __('core.log.event.order_fully_refunded_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'refund_created' => [
            'id'               => 'refund_created',
            'label'            => __('core.log.event.refund_created', 'order-daemon'),
            /* translators: 1: Refund ID number, 2: Order ID number, 3: Refund amount */
            'summary_template' => __('core.log.event.refund_created_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        'refund_deleted' => [
            'id'               => 'refund_deleted',
            'label'            => __('core.log.event.refund_deleted', 'order-daemon'),
            /* translators: 1: Refund ID number, 2: Order ID number */
            'summary_template' => __('core.log.event.refund_deleted_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'order_deleted' => [
            'id'               => 'order_deleted',
            'label'            => __('core.log.event.order_deleted', 'order-daemon'),
            /* translators: 1: Order ID number, 2: User who deleted the order */
            'summary_template' => __('core.log.event.order_deleted_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'core',
        ],
        'order_trashed' => [
            'id'               => 'order_trashed',
            'label'            => __('core.log.event.order_trashed', 'order-daemon'),
            /* translators: 1: Order ID number, 2: User who trashed the order */
            'summary_template' => __('core.log.event.order_trashed_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'core',
        ],
        'order_restored' => [
            'id'               => 'order_restored',
            'label'            => __('core.log.event.order_restored', 'order-daemon'),
            /* translators: 1: Order ID number, 2: User who restored the order */
            'summary_template' => __('core.log.event.order_restored_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'step_timing' => [
            'id'               => 'step_timing',
            'label'            => __('core.log.event.step_timing', 'order-daemon'),
            /* translators: 1: Step name, 2: Execution time in milliseconds */
            'summary_template' => __('core.log.event.step_timing_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'no_match_found' => [
            'id'               => 'no_match_found',
            'label'            => __('core.log.event.no_rules_matched', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.event.no_rules_matched_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'rule_evaluation_start' => [
            'id'               => 'rule_evaluation_start',
            'label'            => __('core.log.event.rule_evaluation_started', 'order-daemon'),
            /* translators: 1: Rule name, 2: Order ID number */
            'summary_template' => __('core.log.event.rule_evaluation_started_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'condition_evaluation' => [
            'id'               => 'condition_evaluation',
            'label'            => __('core.log.event.condition_evaluation', 'order-daemon'),
            /* translators: 1: Condition name, 2: Order ID number, 3: Evaluation result */
            'summary_template' => __('core.log.event.condition_evaluation_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'action_execution_start' => [
            'id'               => 'action_execution_start',
            'label'            => __('core.log.event.action_execution_started', 'order-daemon'),
            /* translators: 1: Action name, 2: Order ID number */
            'summary_template' => __('core.log.event.action_execution_started_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'database_query_executed' => [
            'id'               => 'database_query_executed',
            'label'            => __('core.log.event.database_query_executed', 'order-daemon'),
            /* translators: %s: The database query that was executed */
            'summary_template' => __('core.log.event.database_query_executed_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        // === PREMIUM EVENTS: Advanced feature logging ===
        
        'advanced_condition_matched' => [
            'id'               => 'advanced_condition_matched',
            'label'            => __('core.log.event.advanced_condition_matched', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Premium condition name */
            'summary_template' => __('core.log.event.advanced_condition_matched_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        'custom_email_sent' => [
            'id'               => 'custom_email_sent',
            'label'            => __('core.log.event.custom_email_sent', 'order-daemon'),
            /* translators: 1: Order ID number, 2: Email recipient address */
            'summary_template' => __('core.log.event.custom_email_sent_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        'advanced_action_executed' => [
            'id'               => 'advanced_action_executed',
            'label'            => __('core.log.event.advanced_action_executed', 'order-daemon'),
            /* translators: 1: Premium action name, 2: Order ID number */
            'summary_template' => __('core.log.event.advanced_action_executed_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        'bulk_operation_completed' => [
            'id'               => 'bulk_operation_completed',
            'label'            => __('core.log.event.bulk_operation_completed', 'order-daemon'),
            /* translators: %d: Number of orders processed in the bulk operation */
            'summary_template' => __('core.log.event.bulk_operation_completed_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'premium',
        ],
        
        // === SYSTEM EVENTS: Internal plugin operations ===
        
        'plugin_activated' => [
            'id'               => 'plugin_activated',
            'label'            => __('core.log.event.plugin_activated', 'order-daemon'),
            /* translators: %s: Plugin version number */
            'summary_template' => __('core.log.event.plugin_activated_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        'database_upgraded' => [
            'id'               => 'database_upgraded',
            'label'            => __('core.log.event.database_upgraded', 'order-daemon'),
            /* translators: 1: Previous version number, 2: New version number */
            'summary_template' => __('core.log.event.database_upgraded_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        'settings_updated' => [
            'id'               => 'settings_updated',
            'label'            => __('core.log.event.settings_updated', 'order-daemon'),
            /* translators: %s: Username of the user who updated settings */
            'summary_template' => __('core.log.event.settings_updated_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'debug',
        ],
        
        'cleanup_task' => [
            'id'               => 'cleanup_task',
            'label'            => __('core.log.event.log_cleanup_task', 'order-daemon'),
            /* translators: 1: Number of entries removed, 2: Retention period in days */
            'summary_template' => __('core.log.event.log_cleanup_task_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'core',
        ],
        
        'admin_reprocess_orders' => [
            'id'               => 'admin_reprocess_orders',
            'label'            => __('core.log.event.admin_reprocess_orders', 'order-daemon'),
            /* translators: 1: Admin username, 2: Number of orders reprocessed */
            'summary_template' => __('core.log.event.admin_reprocess_orders_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'core',
        ],
        
        // === TESTING EVENTS: Comprehensive status and component validation ===
        
        // SUCCESS STATUS EVENTS
        'api_call_report' => [
            'id'               => 'api_call_report',
            'label'            => __('core.log.test.api_call_success', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.api_call_success_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        'rule_eval_matched' => [
            'id'               => 'rule_eval_matched',
            'label'            => __('core.log.test.rule_match_success', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.rule_match_success_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        'db_query_success' => [
            'id'               => 'db_query_success',
            'label'            => __('core.log.test.database_success', 'order-daemon'),
            'summary_template' => __('core.log.test.database_success_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        // ERROR STATUS EVENTS
        'error_report_stack_trace' => [
            'id'               => 'error_report_stack_trace',
            'label'            => __('core.log.test.critical_error', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.critical_error_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'debug',
        ],
        
        'db_query_failed' => [
            'id'               => 'db_query_failed',
            'label'            => __('core.log.test.database_error', 'order-daemon'),
            'summary_template' => __('core.log.test.database_error_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'debug',
        ],
        
        // WARNING STATUS EVENTS
        'error_report_simple_string' => [
            'id'               => 'error_report_simple_string',
            'label'            => __('core.log.test.warning_message', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.warning_message_template', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        'db_query_slow' => [
            'id'               => 'db_query_slow',
            'label'            => __('core.log.test.performance_warning', 'order-daemon'),
            'summary_template' => __('core.log.test.performance_warning_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        // INFO STATUS EVENTS
        'performance_report' => [
            'id'               => 'performance_report',
            'label'            => __('core.log.test.performance_info', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.performance_info_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        'woocommerce_report' => [
            'id'               => 'woocommerce_report',
            'label'            => __('core.log.test.woocommerce_info', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.woocommerce_info_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // NOTICE STATUS EVENTS
        'system_info_report' => [
            'id'               => 'system_info_report',
            'label'            => __('core.log.test.system_notice', 'order-daemon'),
            'summary_template' => __('core.log.test.system_notice_message', 'order-daemon'),
            'default_status'   => 'notice',
            'category'         => 'test',
        ],
        
        'rule_eval_no_match' => [
            'id'               => 'rule_eval_no_match',
            'label'            => __('core.log.test.rule_no_match', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.rule_no_match_message', 'order-daemon'),
            'default_status'   => 'notice',
            'category'         => 'test',
        ],
        
        // CRITICAL STATUS EVENTS
        'error_report_wp_error' => [
            'id'               => 'error_report_wp_error',
            'label'            => __('core.log.test.critical_wp_error', 'order-daemon'),
            'summary_template' => __('core.log.test.critical_wp_error_message', 'order-daemon'),
            'default_status'   => 'critical',
            'category'         => 'debug',
        ],
        
        // COMPLETED STATUS EVENTS
        'fallback_data' => [
            'id'               => 'fallback_data',
            'label'            => __('core.log.test.operation_completed', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.operation_completed_message', 'order-daemon'),
            'default_status'   => 'completed',
            'category'         => 'test',
        ],
        
        // DEBUG STATUS EVENTS
        'debug_trace_report' => [
            'id'               => 'debug_trace_report',
            'label'            => __('core.log.test.debug_trace', 'order-daemon'),
            'summary_template' => __('core.log.test.debug_trace_message', 'order-daemon'),
            'default_status'   => 'debug',
            'category'         => 'test',
        ],
        
        // PENDING STATUS EVENTS
        'async_operation_pending' => [
            'id'               => 'async_operation_pending',
            'label'            => __('core.log.test.pending_operation', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.pending_operation_message', 'order-daemon'),
            'default_status'   => 'pending',
            'category'         => 'test',
        ],
        
        // SKIPPED STATUS EVENTS
        'operation_skipped' => [
            'id'               => 'operation_skipped',
            'label'            => __('core.log.test.operation_skipped', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.operation_skipped_message', 'order-daemon'),
            'default_status'   => 'skipped',
            'category'         => 'test',
        ],
               
        // Pure API Events - Only API detection keys
        'pure_api_event' => [
            'id'               => 'pure_api_event',
            'label'            => __('core.log.test.pure_api_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.pure_api_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Pure Database Events - Only database detection keys
        'pure_database_event' => [
            'id'               => 'pure_database_event',
            'label'            => __('core.log.test.pure_database_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.pure_database_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Complex Multi-API Events - Multiple API calls in single payload
        'complex_multi_api_event' => [
            'id'               => 'complex_multi_api_event',
            'label'            => __('core.log.test.complex_multi_api_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.complex_multi_api_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Webhook Processing Events - API + WooCommerce + Performance
        'webhook_processing_event' => [
            'id'               => 'webhook_processing_event',
            'label'            => __('core.log.test.webhook_processing_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.webhook_processing_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Background Task Events - System + Performance + Database
        'background_task_event' => [
            'id'               => 'background_task_event',
            'label'            => __('core.log.test.background_task_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.background_task_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Integration Events - Third-party plugin interactions
        'integration_event' => [
            'id'               => 'integration_event',
            'label'            => __('core.log.test.integration_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.integration_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Import/Export Events - Database + Performance + System + API
        'import_export_event' => [
            'id'               => 'import_export_event',
            'label'            => __('core.log.test.import_export_event', 'order-daemon'),
            'summary_template' => __('core.log.test.import_export_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // === STRESS TEST EVENTS ===
        
        // Large Payload Tests - Very large JSON objects (>100KB)
        'large_payload_stress_test' => [
            'id'               => 'large_payload_stress_test',
            'label'            => __('core.log.test.large_payload_stress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.large_payload_stress_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Deep Nesting Tests - Deeply nested data structures (10+ levels)
        'deep_nesting_stress_test' => [
            'id'               => 'deep_nesting_stress_test',
            'label'            => __('core.log.test.deep_nesting_stress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.deep_nesting_stress_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Long Text Tests - Very long error messages, stack traces (>10,000 chars)
        'long_text_stress_test' => [
            'id'               => 'long_text_stress_test',
            'label'            => __('core.log.test.long_text_stress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.long_text_stress_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'test',
        ],
        
        // Unicode Tests - Special characters, emojis, international text
        'unicode_stress_test' => [
            'id'               => 'unicode_stress_test',
            'label'            => __('core.log.test.unicode_stress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.unicode_stress_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Special Character Tests - HTML entities, SQL injection attempts, XSS
        'special_char_stress_test' => [
            'id'               => 'special_char_stress_test',
            'label'            => __('core.log.test.special_character_stress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.special_char_stress_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        // Memory Stress Tests - Large arrays, binary data representations
        'memory_stress_test' => [
            'id'               => 'memory_stress_test',
            'label'            => __('core.log.test.memory_stress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.memory_stress_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        // Performance Edge Cases - Very slow queries (>10s), memory exhaustion
        'performance_edge_stress_test' => [
            'id'               => 'performance_edge_stress_test',
            'label'            => __('core.log.test.performance_edge_stress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.performance_edge_stress_message', 'order-daemon'),
            'default_status'   => 'critical',
            'category'         => 'test',
        ],
        
        // === INTEGRATION SCENARIO EVENTS ===
        
        // Multi-Component Events - Single events triggering 4+ renderers
        'multi_component_integration' => [
            'id'               => 'multi_component_integration',
            'label'            => __('core.log.test.multi_component_integration', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.multi_component_integration_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Workflow Progression - Related events showing order processing flow
        'workflow_progression_start' => [
            'id'               => 'workflow_progression_start',
            'label'            => __('core.log.test.workflow_start', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.workflow_start_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        'workflow_progression_middle' => [
            'id'               => 'workflow_progression_middle',
            'label'            => __('core.log.test.workflow_progress', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.workflow_progress_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        'workflow_progression_end' => [
            'id'               => 'workflow_progression_end',
            'label'            => __('core.log.test.workflow_complete', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.workflow_complete_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        // Cross-Reference Samples - Events referencing other log entries
        'cross_reference_event' => [
            'id'               => 'cross_reference_event',
            'label'            => __('core.log.test.cross_reference_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.cross_reference_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Time-Series Samples - Events showing progression over time
        'time_series_event' => [
            'id'               => 'time_series_event',
            'label'            => __('core.log.test.time_series_event', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.time_series_event_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Error Recovery Samples - Error → Retry → Success sequences
        'error_recovery_failure' => [
            'id'               => 'error_recovery_failure',
            'label'            => __('core.log.test.recovery_failure', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.recovery_failure_message', 'order-daemon'),
            'default_status'   => 'error',
            'category'         => 'test',
        ],
        
        'error_recovery_retry' => [
            'id'               => 'error_recovery_retry',
            'label'            => __('core.log.test.recovery_retry', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.recovery_retry_message', 'order-daemon'),
            'default_status'   => 'warning',
            'category'         => 'test',
        ],
        
        'error_recovery_success' => [
            'id'               => 'error_recovery_success',
            'label'            => __('core.log.test.recovery_success', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.recovery_success_message', 'order-daemon'),
            'default_status'   => 'success',
            'category'         => 'test',
        ],
        
        // Real-World Scenarios - Complete order processing workflows
        'real_world_order_workflow' => [
            'id'               => 'real_world_order_workflow',
            'label'            => __('core.log.test.real_world_workflow', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.real_world_workflow_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],
        
        // Plugin Interaction Samples - Events from multiple plugins
        'plugin_interaction_event' => [
            'id'               => 'plugin_interaction_event',
            'label'            => __('core.log.test.plugin_interaction', 'order-daemon'),
            /* translators: %d: The order ID number */
            'summary_template' => __('core.log.test.plugin_interaction_message', 'order-daemon'),
            'default_status'   => 'info',
            'category'         => 'test',
        ],

    ];
}

/**
 * Get Log Status Registry - Standardized Status Definitions with UI Styling
 *
 * This function returns a comprehensive registry of all available log statuses
 * that can be used throughout the audit log system. Each status includes
 * display properties for consistent UI rendering and user experience.
 *
 * STATUS SYSTEM OVERVIEW:
 * ======================
 * 
 * The status system provides standardized categorization of log events
 * based on their outcome or severity level. This enables:
 * - Consistent visual representation across the admin interface
 * - Effective filtering and searching capabilities
 * - Clear communication of event importance to users
 * - Standardized CSS styling for status indicators
 * 
 * UI INTEGRATION:
 * ==============
 * 
 * Each status includes a CSS class that corresponds to styling in the
 * plugin's admin.css file. The classes follow the pattern:
 * odcm-status-pill-{status}
 * 
 * This enables consistent "pill" style status indicators throughout
 * the audit trail interface with appropriate colors and styling.
 * 
 * EXTENSIBILITY:
 * =============
 * 
 * New statuses can be added by:
 * 1. Adding entry to this registry function
 * 2. Adding corresponding CSS styles to admin.css
 * 3. Using the new status in event logging calls
 * 
 * The system is designed to be easily extended without breaking
 * existing functionality or requiring code changes elsewhere.
 *
 * @since 1.0.0
 *
 * @return array<string, array<string, string>> {
 *     Associative array of status definitions keyed by status slug.
 *     
 *     @type array $status_slug {
 *         Individual status definition.
 *         
 *         @type string $label     Translatable display text for the status.
 *         @type string $css_class CSS class name for styling the status pill.
 *     }
 * }
 *
 * @example
 * ```php
 * // Get all available statuses
 * $statuses = odcm_get_log_statuses();
 * 
 * // Render status pill in UI
 * $status = 'success';
 * if (isset($statuses[$status])) {
 *     $status_data = $statuses[$status];
 *     echo '<span class="' . esc_attr($status_data['css_class']) . '">';
 *     echo esc_html($status_data['label']);
 *     echo '</span>';
 * }
 * 
 * // Validate status before logging
 * $requested_status = 'custom_status';
 * if (!array_key_exists($requested_status, $statuses)) {
 *     $requested_status = 'info'; // Default fallback
 * }
 * 
 * // Generate status dropdown for filtering
 * foreach ($statuses as $slug => $data) {
 *     echo '<option value="' . esc_attr($slug) . '">';
 *     echo esc_html($data['label']);
 *     echo '</option>';
 * }
 * ```
 */
function odcm_get_log_statuses(): array
{
    return [
        'success' => [
            'label'     => __('core.log.status.success', 'order-daemon'),
            'css_class' => 'odcm-status-pill--success',
            'code'      => 1,
        ],
        
        'error' => [
            'label'     => __('core.log.status.error', 'order-daemon'),
            'css_class' => 'odcm-status-pill--error',
            'code'      => 2,
        ],
        
        'warning' => [
            'label'     => __('core.log.status.warning', 'order-daemon'),
            'css_class' => 'odcm-status-pill--warning',
            'code'      => 3,
        ],
        
        'info' => [
            'label'     => __('core.log.status.info', 'order-daemon'),
            'css_class' => 'odcm-status-pill--info',
            'code'      => 4,
        ],
        
        'notice' => [
            'label'     => __('core.log.status.notice', 'order-daemon'),
            'css_class' => 'odcm-status-pill--notice',
            'code'      => 5,
        ],
        
        'debug' => [
            'label'     => __('core.log.status.debug', 'order-daemon'),
            'css_class' => 'odcm-status-pill--debug',
            'code'      => 6,
        ],
        
        'critical' => [
            'label'     => __('core.log.status.critical', 'order-daemon'),
            'css_class' => 'odcm-status-pill--critical',
            'code'      => 7,
        ],
        
        'pending' => [
            'label'     => __('core.log.status.pending', 'order-daemon'),
            'css_class' => 'odcm-status-pill--notice',
            'code'      => 8,
        ],
        
        'skipped' => [
            'label'     => __('core.log.status.skipped', 'order-daemon'),
            'css_class' => 'odcm-status-pill--notice',
            'code'      => 9,
        ],
        
        'completed' => [
            'label'     => __('core.log.status.completed', 'order-daemon'),
            'css_class' => 'odcm-status-pill--success',
            'code'      => 10,
        ],
    ];
}

/**
 * Get Log Sources Registry - Sources of audit log events with encoding
 *
 * @since 1.0.0
 * @return array<string, array<string, mixed>>
 */
function odcm_get_log_sources(): array
{
    return [
        'system' => [
            'label' => __('core.log.source.system', 'order-daemon'),
            'code'  => 1,
        ],
        'manual' => [
            'label' => __('core.log.source.manual', 'order-daemon'), 
            'code'  => 2,
        ],
        'webhook' => [
            'label' => __('core.log.source.webhook', 'order-daemon'),
            'code'  => 3,
        ],
        'api' => [
            'label' => __('core.log.source.api', 'order-daemon'),
            'code'  => 4,
        ],
        'scheduled' => [
            'label' => __('core.log.source.scheduled', 'order-daemon'),
            'code'  => 5,
        ],
        'processor' => [
            'label' => __('core.log.source.event_processor', 'order-daemon'),
            'code'  => 6,
        ],
        'logger' => [
            'label' => __('core.log.source.logger', 'order-daemon'),
            'code'  => 7,
        ],
    ];
}

/**
 * Encode status string to integer code
 *
 * @param string $status Status string
 * @return int Status code
 */
function odcm_encode_status(string $status): int 
{
    $statuses = odcm_get_log_statuses();
    return $statuses[$status]['code'] ?? 4; // Default to 'info'
}

/**
 * Decode status code to string
 *
 * @param int $code Status code
 * @return string Status string
 */
function odcm_decode_status(int $code): string 
{
    static $reverse_map = null;
    if ($reverse_map === null) {
        $statuses = odcm_get_log_statuses();
        foreach ($statuses as $status => $data) {
            $reverse_map[$data['code']] = $status;
        }
    }
    return $reverse_map[$code] ?? 'info';
}

/**
 * Encode source string to integer code
 *
 * @param string $source Source string
 * @return int Source code
 */
function odcm_encode_source(string $source): int 
{
    $sources = odcm_get_log_sources();
    return $sources[$source]['code'] ?? 1; // Default to 'system'
}

/**
 * Decode source code to string
 *
 * @param int $code Source code
 * @return string Source string
 */
function odcm_decode_source(int $code): string 
{
    static $reverse_map = null;
    if ($reverse_map === null) {
        $sources = odcm_get_log_sources();
        foreach ($sources as $source => $data) {
            $reverse_map[$data['code']] = $source;
        }
    }
    $result = $reverse_map[$code] ?? 'system';
    return (string) $result; // Ensure we always return a string
}
